### PR TITLE
[FIX] dependencies

### PR DESCRIPTION
**Pull request by AFcgi**

### CODE REVIEW

**Comment by at-daonv** [comment]
what wrong with `~> 0.98.0`?

**Comment by AFcgi** [comment]
It's the same issue like ObjectMapper. The standardized specification is only one point notation, f.e. <code>~> 0.98</code> or <code>~> 1.1</code>.

**Comment by zendobk** [comment]
Realm > 0.98.5 use Swift 2.2, will be supported in RealmMapper ~ 1.1.x, not in 1.0.x.
I'm busy now, any update will be pushed in weekend. Thanks you!

**Comment by AFcgi** [comment]
Thanks. I try the RealmMapper with Realm 0.98.8 and ObjectMapper 1.2 and it work fine.

**Comment by zendobk** [comment]
Ok I'm checking now. There are some failures report from Travis.

**Comment by zendobk** [comment]
ObjectMapper 1.2 use Swift 2.2. It'll be updated with RealmMapper 1.1+, thanks you!

**Pull request closed without merging**
